# Site settings
title: Android Test Part of Jetpack
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the official page for the Android Test Library, a library provided by Google for testing Android apps.
baseurl: "/android-test" # the subpath of your site, e.g. /blog/
url: "https://android.github.io" # the base hostname & protocol for your site
sourceUrl: "https://android.github.io/android-test"

# Build settings
markdown: kramdown

# Define version numbers for library artifacts
atslVersion: 1.0.2
espressoVersion: 3.0.2
uiautomatorVersion: 2.1.2

gems:
  - octopress-autoprefixer
  - jekyll-redirect-from
